name: CI Pipeline

# 1. Trigger: When does this workflow run?
on:
  push:
    branches: ["main", "develop"] # Run on pushes to main or develop
  pull_request:
    branches: ["main"] # Also run on pull requests targeting main

# 2. Jobs: What tasks should be performed?
jobs:
  build-and-test:
    # 3. Environment: What kind of machine should this run on?
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    # 4. Steps: The sequence of commands to execute
    steps:
      # Step 1: Check out the repository's code
      - name: Check out code
        uses: actions/checkout@v4
      # Step 2: Ste up the specific Python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Step 3: Install dependencies
      # Install dependencies including pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Step 4: Install the project package itself
      - name: Install project package
        run: pip install -e .
      # Step 5: Run the tests: If this step fails, the entire workflow fails
      - name: Run tests with pytest
        run: pytest
